export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    sqlite: "SQLite",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    nest: "NestJS",
    rn: "React-Native",
    kmm: "Kotlin Multiplatform",
    node: "Node.js",
    docker: "Docker",
    firebase: "Firebase",
    node: "Node.js",
    vscode: "VSCode",
    jenkins: "Jenkins",
    git: "Git & GitHub",
    react: "React",
    discordJs: "Discord.js",
    express: "Express",
    rust: "Rust",
    androidstudio: "Android Studio",
    kotlin: "Kotlin",
    dart: "Dart",
    flutter: "Flutter"
}